### ISSUE TITLE
feature: pythonw support

### ISSUE THREAD

**Issue by zeratax** [limitedeternity/pyenv-py#4]
it would be great if .pyw files would open with pythonw with this

**Comment by limitedeternity** [comment]
That's not possible by design. However, you can build a separate binary (called, let's say, `pyw.exe`) from the same source to invoke `pythonw.exe` within pyenv.

**Comment by limitedeternity** [comment]
To do so,

1. Replace `"python"` with `"pythonw"` there: https://github.com/limitedeternity/pyenv-py/blob/36d5ae9eee2d8031e5a0c38796481443de6b1f58/src/main.rs#L185
2. Replace `"py"` with `"pyw"` there: https://github.com/limitedeternity/pyenv-py/blob/36d5ae9eee2d8031e5a0c38796481443de6b1f58/Cargo.toml#L7
3. Run `cargo install --path .`

After that you'll have `py.exe` and `pyw.exe` on your machine.

**Comment by limitedeternity** [comment]
Until https://github.com/rust-lang/rfcs/pull/3374 is implemented, there is no way to produce two different binaries from the same source in one go.

However, I can add a `pythonw` feature to `Cargo.toml` so that it's possible to produce a `py.exe` which runs `pythonw` instead of `python`.

The command for that will be: `cargo build --release --features pythonw`. Want me to do that?
